import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const datas = require("/public/article/data.json");

  return (
    <>
      <Head>
        <title>Yoonjong Park&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <nav>
          <div className={styles.description}>
            <p>Yoonjong Park&#39;s Portfolio</p>
          </div>
        </nav>

        <div className={styles.center}>
          <h2 className={inter.className}>Front-end Article Cloud</h2>
          <article className={inter.className}>
            프론트엔드에 관련된 개발 자료를 모읍니다.
          </article>
        </div>

        <div className={styles.grid}>
          {datas?.map((data: any) => (
            <a
              key={data.id}
              href={data.url}
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer">
              <h2 className={inter.className}>{data.title}</h2>
              <p className={inter.className}>
                {data.description.length > 40
                  ? data.description.substr(0, 40) + "..."
                  : data.description}
              </p>
            </a>
          ))}
        </div>
      </main>

      <footer className={styles.logoBox}>
        <a
          className={styles.logo}
          href="mailto:yoonjongpark@gmail.com?Subject=제안합니다."
          target="_blank"
          rel="noopener noreferrer">
          <div>yoonjongpark@gmail.com</div>
        </a>

        <a
          className={styles.logo}
          href="https://github.com/yoonjong-park"
          target="_blank"
          rel="noopener noreferrer">
          <div>github</div>
        </a>
        <a
          className={styles.logo}
          href="https://yoonjong-park.tistory.com/"
          target="_blank"
          rel="noopener noreferrer">
          <div>blog</div>
        </a>
        <a
          className={styles.logo}
          href="https://www.linkedin.com/in/yoonjong-park-a98b7062/"
          target="_blank"
          rel="noopener noreferrer">
          <div>linkedin</div>
        </a>
      </footer>
    </>
  );
}
